name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        always-auth: false

    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        sudo apt-get -y install cpp-aarch64-linux-gnu gccgo-aarch64-linux-gnu make git

    - name: Build
      run: |
            make tar_all_ci

    - uses: actions/upload-artifact@v2
      with:
            name: v2ray-webui-master.tar.gz
            path: v2ray-webui-master.tar.gz
  
    - uses: actions/upload-artifact@v2
      with:
            name: v2ray-webui-master-arm.tar.gz
            path: v2ray-webui-master-arm.tar.gz
            

    - name: Test
      run: go test -v .
